CREATE TABLE EVENTS 
   (APN VARCHAR(50), 
	A_NUMBER VARCHAR(100), 
	B_NUMBER VARCHAR(100), 
	CELL_ID VARCHAR(20), 
	COMPANY_ID NUMERIC(18,0) NOT NULL, 
	C_NUMBER VARCHAR(100), 
	CREATED_DAY DATE DEFAULT date_trunc('day',CURRENT_DATE), 
	CREATED_DATE DATE DEFAULT CURRENT_DATE, 
	ENTITY_ID VARCHAR(100), 
	EVENT_DAY DATE, 
	EVENT_DIRECTION VARCHAR(5), 
	EVENT_DURATION NUMERIC(20,0), 
	EVENT_ID NUMERIC(38,0), 
	EVENT_START_DATE DATE, 
	EVENT_TYPE_ID NUMERIC(5,0), 
	HOME_NETWORK_COUNTRY_ID NUMERIC(5,0), 
	IMEI VARCHAR(16), 
	IMSI VARCHAR(15), 
	ORIG_DEST_COUNTRY_ID NUMERIC(5,0),
	TRAFFIC_TYPE_ID NUMERIC(5,0),
	VISITED_NETWORK_COUNTRY_ID NUMERIC(5,0)
   );

CREATE TABLE ALARMS 
   (ALARM_ID NUMERIC(18,0), 
	ALARM_SCORE NUMERIC(18,0), 
	ENTITY_ID VARCHAR(64), 
	ORDER_ID NUMERIC(18,0), 
	STATUS_ID NUMERIC(1,0), 
	HITS NUMERIC(18,0), 
	ALARM_TYPE NUMERIC(18,0),
	ALARM_STATUS NUMERIC(1,0), 
	COMPANY_ID NUMERIC(10,0), 
	PRIORITY NUMERIC(18,0), 
	FRAUD_TYPE NUMERIC(18,0), 
	ORIGINAL_ENTITY_ID VARCHAR(64)
   );
   
CREATE TABLE HIGHRISK_LIST 
   (ENTRY_UUID VARCHAR(50), 
	VALUE VARCHAR(50), 
	DESCRIPTION VARCHAR(512), 
	VALID VARCHAR(1)
	);
   
CREATE TABLE TRAFFIC_TYPE 
   (TRAFFIC_TYPE_ID NUMERIC(10,0), 
	SHDESC VARCHAR(50),
    DESCRIPTION VARCHAR(100)
   );   
   